name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Setup Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # tag=v2
        with:
          go-version: 1.16
      - name: Import GPG Key
        uses: hashicorp/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        id: gpg
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: >-
            release
            --config ${{github.workspace}}/.github/goreleaser.yml
            --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ github.token }}

