name: Tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Setup Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # tag=v3
        with:
          go-version: 1.16
      - name: Find Module Cache Directory
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-mod-cache
      - name: Restore Module Cache
        uses: actions/cache@30f413bfed0a2bc738fdfd409e5a9e96b24545fd # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: ${{ steps.go-mod-cache.outputs.dir }}
      - name: Update Dependencies
        run: go mod download
      - name: Build
        run: go build -v ${{github.workspace}}
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        terraform: ['0.15.3']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Setup Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # tag=v3
        with:
          go-version: 1.16
      - name: Find Module Cache Directory
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-mod-cache
      - name: Restore Module Cache
        uses: actions/cache@30f413bfed0a2bc738fdfd409e5a9e96b24545fd # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-
          path: ${{ steps.go-mod-cache.outputs.dir }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Update Dependencies
        run: go mod download
      - name: Terraform Acceptance Tests
        run: >-
          go test -v
          -race
          -coverprofile coverage.out
          -covermode=atomic
          -cover ${{github.workspace}}/env
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
          TF_ACC: 1
      - name: Upload Code Coverage
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # tag=v3.1.0
        with:
          fail_ci_if_error: true
          directory: ${{ github.workspace }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
