name: Tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3
      - name: Setup Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3
        with:
          go-version: 1.x
      - name: Find Module Cache Directory
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-mod-cache
      - name: Restore Module Cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: ${{ steps.go-mod-cache.outputs.dir }}
      - name: Update Dependencies
        run: go mod download
      - name: Build
        run: go build -v ${{github.workspace}}
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        terraform: ['1.1.*', '1.2.*']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3
      - name: Setup Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3
        with:
          go-version: 1.x
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # tag=v2
        with:
          terraform_version: ${{matrix.terraform}}
          terraform_wrapper: false
      - name: Find Module Cache Directory
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-mod-cache
      - name: Restore Module Cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        with:
          restore-keys: ${{ runner.os }}-go-
          path: ${{ steps.go-mod-cache.outputs.dir }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Update Dependencies
        run: go mod download
      - name: Terraform Acceptance Tests
        run: >-
          go test -v
          -race
          -coverprofile coverage.out
          -covermode=atomic
          -cover ${{github.workspace}}/env
        env:
          TF_ACC: 1
      - name: Upload Code Coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        with:
          fail_ci_if_error: true
          directory: ${{ github.workspace }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
